export const FLOWER_QUESTIONS = [
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/sunflower.jpg',
    options: ['חמנייה', 'רקפת', 'כלנית'],
    answer: 0,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/anemone.jpg',
    options: ['נרקיס', 'כלנית', 'חמנייה'],
    answer: 1,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/cyclamen.jpg',
    options: ['רקפת', 'ורד', 'סחלב'],
    answer: 0,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/dahlia.jpg',
    options: ['חרצית', 'דליה', 'פרג'],
    answer: 1,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/rose.jpg',
    options: ['ורד', 'כלנית', 'צבעוני'],
    answer: 0,
  },
  {
    question: 'מה שם העץ בתמונה?',
    image: '/images/flowers/olive-tree.jpg',
    options: ['אורן', 'עץ זית', 'אקליפטוס'],
    answer: 1,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/iris.jpg',
    options: ['לבנדר', 'אירוס', 'סיגלית'],
    answer: 1,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/tulip.jpg',
    options: ['נרקיס', 'חמנייה', 'צבעוני'],
    answer: 2,
  },
  {
    question: 'מה שם העץ בתמונה?',
    image: '/images/flowers/carob-tree.jpg',
    options: ['עץ חרוב', 'עץ תאנה', 'עץ רימון'],
    answer: 0,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/lavender.jpg',
    options: ['אירוס', 'סיגלית', 'לבנדר'],
    answer: 2,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/narcissus.jpg',
    options: ['נרקיס', 'חמנייה', 'צבעוני'],
    answer: 0,
  },
  {
    question: 'מה שם העץ בתמונה?',
    image: '/images/flowers/pine-tree.jpg',
    options: ['אקליפטוס', 'ברוש', 'אורן'],
    answer: 2,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/poppy.jpg',
    options: ['כלנית', 'פרג', 'ורד'],
    answer: 1,
  },
  {
    question: 'מה שם העץ בתמונה?',
    image: '/images/flowers/fig-tree.jpg',
    options: ['עץ זית', 'עץ תאנה', 'עץ חרוב'],
    answer: 1,
  },
  {
    question: 'מה שם הפרח בתמונה?',
    image: '/images/flowers/chrysanthemum.jpg',
    options: ['דליה', 'חרצית', 'רקפת'],
    answer: 1,
  },
];
